# Generated by Django 5.1.1 on 2024-09-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="name",
            new_name="city",
        ),
        migrations.AddField(
            model_name="userdata",
            name="address_line1",
            field=models.CharField(default="N/A", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdata",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="first_name",
            field=models.CharField(default="Anonymous", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdata",
            name="last_name",
            field=models.CharField(default="Anonymous", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdata",
            name="postal_code",
            field=models.CharField(default="N/A", max_length=20),
            preserve_default=False,
        ),
    ]
