# Generated by Django 5.1.1 on 2024-09-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_name_userdata_city_userdata_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="address_line1",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="city",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="email",
            field=models.EmailField(default="N/A", max_length=500),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="first_name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="last_name",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="postal_code",
            field=models.CharField(default="N/A", max_length=20),
        ),
    ]
